function lang() {
  var lang = [['Acèh','ace'],
              ['Afrikaans','af'],
              ['Akan','ak'],
              ['Alemannisch','als'],
              ['aragonés','an'],
              ['armãneashti','roa-rup'],
              ['arpetan','frp'],
              ['asturianu','ast'],
              ['Atikamekw','atj'],
              ['Avañe ẽ','gn'],
              ['Aymar aru','ay'],
              ['azərbaycanca','az'],
              ['Bahasa Banjar','bjn'],
              ['Bahasa Hulontalo','gor'],
              ['Bahasa Indonesia','id'],
              ['Bahasa Melayu','ms'],
              ['bamanankan','bm'],
              ['Basa Banyumasan','map-bms'],
              ['Basa Jawa','jv'],
              ['Basa Sunda','su'],
              ['Baso Minangkabau','min'],
              ['Bikol Central','bcl'],
              ['Bislama','bi'],
              ['Boarisch','bar'],
              ['bosanski','bs'],
              ['brezhoneg','br'],
              ['Bân-lâm-gú','zh-min-nan'],
              ['català','ca'],
              ['Cebuano','ceb'],
              ['Chamoru','ch'],
              ['Chavacano de Zamboanga','cbk-zam'],
              ['Chi-Chewa','ny'],
              ['chiShona','sn'],
              ['chiTumbuka','tum'],
              ['Choctaw','cho'],
              ['corsu','co'],
              ['Cymraeg','cy'],
              ['dansk','da'],
              ['davvisámegiella','se'],
              ['Deitsch','pdc'],
              ['Deutsch','de'],
              ['Diné bizaad','nv'],
              ['dolnoserbski','dsb'],
              ['Dorerin Naoero','na'],
              ['Ebon','mh'],
              ['eesti','et'],
              ['emiliàn e rumagnòl','eml'],
              ['English','en'],
              ['español','es'],
              ['Esperanto','eo'],
              ['estremeñu','ext'],
              ['euskara','eu'],
              ['eʋegbe','ee'],
              ['Fiji Hindi','hif'],
              ['français','fr'],
              ['Frysk','fy'],
              ['Fulfulde','ff'],
              ['furlan','fur'],
              ['føroyskt','fo'],
              ['Gaeilge','ga'],
              ['Gaelg','gv'],
              ['Gagana Samoa','sm'],
              ['Gagauz','gag'],
              ['galego','gl'],
              ['Gàidhlig','gd'],
              ['Gĩkũyũ','ki'],
              ['Hausa','ha'],
              ['Hawaiʻi','haw'],
              ['Hiri Motu','ho'],
              ['hornjoserbsce','hsb'],
              ['hrvatski','hr'],
              ['Ido','io'],
              ['Igbo','ig'],
              ['Ilokano','ilo'],
              ['interlingua','ia'],
              ['Interlingue','ie'],
              ['isiXhosa','xh'],
              ['isiZulu','zu'],
              ['italiano','it'],
              ['Iñupiak','ik'],
              ['Kabɩyɛ','kbp'],
              ['kalaallisut','kl'],
              ['Kanuri','kr'],
              ['Kapampangan','pam'],
              ['kaszëbsczi','csb'],
              ['kernowek','kw'],
              ['Kinyarwanda','rw'],
              ['Kirundi','rn'],
              ['Kiswahili','sw'],
              ['Kongo','kg'],
              ['Kreyòl ayisyen','ht'],
              ['kurdî','ku'],
              ['Kwanyama','kj'],
              ['la .lojban.','jbo'],
              ['Ladino','lad'],
              ['latgaļu','ltg'],
              ['Latina','la'],
              ['latviešu','lv'],
              ['lea faka-Tonga','to'],
              ['lietuvių','lt'],
              ['Ligure','lij'],
              ['Limburgs','li'],
              ['Lingua Franca Nova','lfn'],
              ['lingála','ln'],
              ['Livvinkarjala','olo'],
              ['Luganda','lg'],
              ['lumbaart','lmo'],
              ['Lëtzebuergesch','lb'],
              ['magyar','hu'],
              ['Malagasy','mg'],
              ['Malti','mt'],
              ['Mirandés','mwl'],
              ['Mvskoke','mus'],
              ['Mìng-dĕ̤ng-ngṳ̄','cdo'],
              ['Māori','mi'],
              ['Na Vosa Vakaviti','fj'],
              ['Napulitano','nap'],
              ['Nederlands','nl'],
              ['Nedersaksies','nds-nl'],
              ['Nordfriisk','frr'],
              ['Norfuk / Pitkern','pih'],
              ['norsk','no'],
              ['norsk nynorsk','nn'],
              ['Nouormand','nrm'],
              ['Novial','nov'],
              ['Nāhuatl','nah'],
              ['Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ','cr'],
              ['occitan','oc'],
              ['Oromoo','om'],
              ['Oshiwambo','ng'],
              ['Otsiherero','hz'],
              ['oʻzbekcha/ўзбекча','uz'],
              ['Pangasinan','pag'],
              ['Papiamentu','pap'],
              ['Patois','jam'],
              ['Picard','pcd'],
              ['Piemontèis','pms'],
              ['Plattdüütsch','nds'],
              ['polski','pl'],
              ['português','pt'],
              ['Pälzisch','pfl'],
              ['Qafár af','aa'],
              ['Qaraqalpaqsha','kaa'],
              ['qırımtatarca','crh'],
              ['reo tahiti','ty'],
              ['Ripoarisch','ksh'],
              ['Romani','rmy'],
              ['română','ro'],
              ['rumantsch','rm'],
              ['Runa Simi','qu'],
              ['sardu','sc'],
              ['Scots','sco'],
              ['Seeltersk','stq'],
              ['Sesotho','st'],
              ['Sesotho sa Leboa','nso'],
              ['Setswana','tn'],
              ['shqip','sq'],
              ['sicilianu','scn'],
              ['Simple English','simple'],
              ['SiSwati','ss'],
              ['slovenčina','sk'],
              ['slovenščina','sl'],
              ['Soomaaliga','so'],
              ['Sranantongo','srn'],
              ['srpskohrvatski / српскохрватски','sh'],
              ['suomi','fi'],
              ['svenska','sv'],
              ['Sängö','sg'],
              ['Tagalog','tl'],
              ['Taqbaylit','kab'],
              ['tarandíne','roa-tara'],
              ['tetun','tet'],
              ['Thuɔŋjäŋ','din'],
              ['Tiếng Việt','vi'],
              ['Tok Pisin','tpi'],
              ['Tsetsêhestâhese','chy'],
              ['Tshivenda','ve'],
              ['Twi','tw'],
              ['Türkmençe','tk'],
              ['Türkçe','tr'],
              ['Vahcuengh','za'],
              ['vepsän kel','vep'],
              ['Volapük','vo'],
              ['vèneto','vec'],
              ['Võro','fiu-vro'],
              ['walon','wa'],
              ['West-Vlams','vls'],
              ['Winaray','war'],
              ['Wolof','wo'],
              ['Xitsonga','ts'],
              ['Yorùbá','yo'],
              ['Zazaki','diq'],
              ['Zeêuws','zea'],
              ['Ænglisc','ang'],
              ['íslenska','is'],
              ['čeština','cs'],
              ['ślůnski','szl'],
              ['žemaitėška','bat-smg'],
              ['Ελληνικά','el'],
              ['Ποντιακά','pnt'],
              ['авар','av'],
              ['адыгабзэ','ady'],
              ['Адыгэбзэ','kbd'],
              ['Аҧсшәа','ab'],
              ['башҡортса','ba'],
              ['беларуская','be'],
              ['беларуская (тарашкевіца)‎','be-tarask'],
              ['буряад','bxr'],
              ['български','bg'],
              ['ГӀалгӀай','inh'],
              ['Ирон','os'],
              ['коми','kv'],
              ['къарачай-малкъар','krc'],
              ['Кыргызча','ky'],
              ['кырык мары','mrj'],
              ['лакку','lbe'],
              ['лезги','lez'],
              ['македонски','mk'],
              ['мокшень','mdf'],
              ['монгол','mn'],
              ['нохчийн','ce'],
              ['олык марий','mhr'],
              ['Перем Коми','koi'],
              ['русиньскый','rue'],
              ['русский','ru'],
              ['саха тыла','sah'],
              ['словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ','cu'],
              ['српски / srpski','sr'],
              ['татарча/tatarça','tt'],
              ['тоҷикӣ','tg'],
              ['тыва дыл','tyv'],
              ['удмурт','udm'],
              ['українська','uk'],
              ['хальмг','xal'],
              ['Чӑвашла','cv'],
              ['эрзянь','myv'],
              ['қазақша','kk'],
              ['հայերեն','hy'],
              ['ייִדיש','yi'],
              ['עברית','he'],
              ['ئۇيغۇرچە / Uyghurche','ug'],
              ['اردو','ur'],
              ['العربية','ar'],
              ['تۆرکجه','azb'],
              ['سنڌي','sd'],
              ['فارسی','fa'],
              ['لۊری شومالی','lrc'],
              ['مازِرونی','mzn'],
              ['مصرى','arz'],
              ['پنجابی','pnb'],
              ['پښتو','ps'],
              ['کوردی','ckb'],
              ['گیلکی','glk'],
              ['ܐܪܡܝܐ','arc'],
              ['ދިވެހިބަސް','dv'],
              ['कॉशुर / کٲشُر','ks'],
              ['गोंयची कोंकणी / Gõychi Konknni','gom'],
              ['डोटेली','dty'],
              ['नेपाल भाषा','new'],
              ['नेपाली','ne'],
              ['पालि','pi'],
              ['भोजपुरी','bh'],
              ['मराठी','mr'],
              ['मैथिली','mai'],
              ['संस्कृतम्','sa'],
              ['हिन्दी','hi'],
              ['অসমীয়া','as'],
              ['বাংলা','bn'],
              ['বিষ্ণুপ্রিয়া মণিপুরী','bpy'],
              ['ਪੰਜਾਬੀ','pa'],
              ['ગુજરાતી','gu'],
              ['ଓଡ଼ିଆ','or'],
              ['தமிழ்','ta'],
              ['తెలుగు','te'],
              ['ಕನ್ನಡ','kn'],
              ['ತುಳು','tcy'],
              ['മലയാളം','ml'],
              ['සිංහල','si'],
              ['ไทย','th'],
              ['ລາວ','lo'],
              ['ཇོང་ཁ','dz'],
              ['བོད་ཡིག','bo'],
              ['မြန်မာဘာသာ','my'],
              ['მარგალური','xmf'],
              ['ქართული','ka'],
              ['ትግርኛ','ti'],
              ['አማርኛ','am'],
              ['ᐃᓄᒃᑎᑐᑦ/inuktitut','iu'],
              ['ភាសាខ្មែរ','km'],
              ['ᨅᨔ ᨕᨘᨁᨗ','bug'],
              ['ᱥᱟᱱᱛᱟᱲᱤ','sat'],
              ['中文','zh'],
              ['吴语','wuu'],
              ['客家語/Hak-kâ-ngî','hak'],
              ['文言','zh-classical'],
              ['日本語','ja'],
              ['粵語','zh-yue'],
              ['贛語','gan'],
              ['ꆇꉙ','ii'],
              ['ᏣᎳᎩ','chr'],
              ['한국어','ko'],
              ['𐌲𐌿𐍄𐌹𐍃𐌺','got']];
  select = document.createElement("select");
  for (i in lang) {
    var opt = document.createElement("option");
    opt.value = lang[i][1];
    opt.innerHTML = lang[i][0];
    if (lang[i][1] == "en") {
      opt.setAttribute("selected","");
    }
    select.append(opt)
  }
  select.addEventListener("change",function(e) {
    tree.changelang(e.target.value)
  })
  document.getElementById("mainform").append(select)
}
lang()
